spring:

  datasource:
    url: jdbc:h2:~/letswork
    username: work
    password: work
    driverClassName: org.h2.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddlAuto: create
    openInView: false

  h2:
    console:
      enabled: true
      path: /h2

  banner:
    location: banner.txt
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
