spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/lets-work
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddlAuto: create
    openInView: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  banner:
    location: banner.txt
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
